concurrent = "${concurrent}"
check_interval = 0

[[runners]]
  name = "${name}"
  url = "${url}"
  token = "${token}"
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "alpine:latest"
    privileged = true
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
  [runners.cache]
